apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: csc-cnv
  namespace: openshift-marketplace
spec:
  targetNamespace: openshift-cnv
  packages: kubevirt-hyperconverged-operator
  source: redhat-operators