---
- name: create bastion instance on osp
  hosts: localhost
  connection: local
  roles:
  - bastion-installer
  vars:
    os_cloud: "rhos-d"
    external_network: "provider_net_shared_3"
    bastion_flavor: m1.large

- debug:
    msg: "Do 'ssh-add {{ ansible_ssh_private_key_file }}' if permission denied"

- name: install required software on bastion
  hosts: bastion
  roles:
  - bastion
  vars:
    redhat_subscription_username: "chainzeeli12"
    redhat_subscription_password: "M@rkGPA4.01996"
  tags: deps