---
# tasks file for cnv
- block:
  - name: install python openshift module
    command: pip3 install openshift

  - name: Create Resources for HCO install
    k8s:
      state: present
      definition: "{{ lookup('file', '{{ item }}') }}"
    with_items:
    - 'project.yaml'
    - 'operatorgroup.yaml'
    - 'sub.yaml'
    - 'cnv-hco.yaml'

  - name: Wait for CNV installation to  finish
    wait_for:
      delay: 60

  - name: Kubervirt installation done
    debug:
      msg: "Kubervirt hco is now in project openshift-cnv"

tags: [install, cnv]