---
# tasks file for pre-install
- name: Create ocp4 cluster
  tags: [install, config]
  include_tasks: create_cluster.yml

- name: Install CNV
  tags: [install, cnv]
  include_tasks: install_cnv.yml

- name: Destroy ocp4 cluster
  tags: destroy
  include_tasks: destroy_cluster.yml
  


















